---
name: ToolSet-XDG
version: 0.03
author:
  - 'David A Golden <dagolden@cpan.org>'
abstract: ToolSet with common features for DAGOLDEN
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Data::Dump::Streamer: 0
  File::Spec: 0
  Perl6::Say: 0
  Scalar::Util: 0
  ToolSet: 0
  perl: 5.006
provides:
  XDG:
    file: lib/XDG.pm
    version: 0.03
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
